"use client"

import React from 'react';
import { Clock, MapPin, Compass } from 'lucide-react';

interface ItineraryStop {
  name: string;
  type?: string;
  description?: string;
  time?: string;
  lat: number;
  lng: number;
  status?: string;
}

type ItineraryType = Record<string, ItineraryStop[]>;

interface PrintableItineraryProps {
  city: string;
  itinerary: ItineraryType | null;
  days: string;
}

export function PrintableItinerary({ city, itinerary, days }: PrintableItineraryProps) {
  if (!itinerary) return null;

  return (
    <div id="printable-itinerary-content" className="bg-white text-[#484848] font-sans w-[800px] fixed top-0 left-0 -z-50 pointer-events-none">
      
      {/* ── Page 1/Cover & Intro Header ───────────────────────── */}
      <div className="p-16 border-b-2 border-[#EBEBEB]">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-12 h-12 bg-[#FF5A5F]/10 rounded-2xl flex items-center justify-center text-[#FF5A5F]">
            <Compass className="h-6 w-6" />
          </div>
          <p className="text-sm font-bold tracking-widest uppercase text-[#767676]">Personalized Itinerary</p>
        </div>
        
        <h1 className="text-6xl font-black text-[#484848] tracking-tighter leading-tight mb-4">
          Explore <span className="text-[#FF5A5F]">{city}</span>
        </h1>
        <p className="text-xl font-medium text-[#767676] max-w-lg">
          A meticulously crafted {days}-day journey, designed exclusively for your travel preferences.
        </p>
      </div>

      {/* ── The Itinerary Timeline ────────────────────────────── */}
      <div className="p-16 space-y-16">
        {Object.entries(itinerary).map(([day, activities]: [string, ItineraryStop[]], idx) => (
          <div key={day} className="relative">
            
            {/* Day Header */}
            <div className="flex items-center gap-6 mb-8 pb-4 border-b border-[#EBEBEB]">
              <div className="w-16 h-16 rounded-full bg-[#FF5A5F] text-white flex items-center justify-center font-black text-2xl shadow-sm shrink-0">
                {idx + 1}
              </div>
              <div>
                <h2 className="text-2xl font-black tracking-tight text-[#484848] uppercase">{day}</h2>
                <div className="flex items-center gap-2 mt-1">
                  <MapPin className="h-4 w-4 text-[#767676]" />
                  <p className="text-sm font-bold text-[#767676] uppercase tracking-wider">{city} Exploration</p>
                </div>
              </div>
            </div>

            {/* Activities */}
            <div className="space-y-8 pl-8">
              {activities.map((act, aIdx) => (
                <div key={aIdx} className="relative pl-8 border-l-2 border-[#EBEBEB]">
                  {/* Timeline Dot */}
                  <div className="absolute -left-[9px] top-1 w-4 h-4 rounded-full bg-white border-4 border-[#00A699]" />
                  
                  <div className="flex items-baseline gap-4 mb-2">
                    <div className="flex items-center gap-1.5 text-[#FF5A5F] font-bold shrink-0">
                      <Clock className="h-4 w-4" />
                      <span>{act.time}</span>
                    </div>
                    {act.type && (
                      <span className="text-[10px] font-bold text-[#767676] bg-[#F7F7F7] px-2 py-0.5 rounded-md uppercase tracking-widest border border-[#EBEBEB]">
                        {act.type}
                      </span>
                    )}
                  </div>
                  
                  <h3 className="text-xl font-bold text-[#484848] mb-2 leading-snug">{act.name}</h3>
                  <p className="text-sm text-[#767676] leading-relaxed max-w-xl">{act.description}</p>
                </div>
              ))}
            </div>

          </div>
        ))}
      </div>

      {/* ── Footer Branding ───────────────────────────────────── */}
      <div className="p-16 pt-8 text-center border-t border-[#EBEBEB] mt-16 bg-[#F7F7F7]">
        <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#BBBBBB] mb-2">Generated by</p>
        <p className="text-xl font-black text-[#484848] tracking-widest">YĀTRĀ</p>
        <p className="text-xs text-[#767676] mt-2">The AI Travel Planner for India</p>
      </div>

    </div>
  );
}
