import jsPDF from 'jspdf';
import { toPng } from 'html-to-image';

export const exportElementToPDF = async (
  elementId: string, 
  fileName: string = 'YatraMatrix-Itinerary.pdf',
  title: string = 'Trips Itinerary'
) => {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error('PDF Export Error: Element not found -', elementId);
    return;
  }

  try {
    // Hide utility buttons temporarily (like "More" options or the export button itself)
    const buttonsToHide = element.querySelectorAll('button');
    const originalDisplays: string[] = [];
    buttonsToHide.forEach(btn => {
      originalDisplays.push(btn.style.display);
      btn.style.display = 'none';
    });

    // Expand the container to ensure full scrollable content is captured
    const originalHeight = element.style.height;
    const originalOverflow = element.style.overflow;
    const originalMaxHeight = element.style.maxHeight;

    element.style.height = 'max-content';
    element.style.overflow = 'visible';
    element.style.maxHeight = 'none';

    // Capture the DOM using native browser rendering (SVGs) instead of JS CSS Parsing
    // This supports modern Tailwind v4 colors like `oklch` which crash html2canvas
    const imgData = await toPng(element, { 
        cacheBust: true,
        pixelRatio: 2,
        backgroundColor: '#ffffff',
        skipFonts: true, // Crucial for ignoring CORS webfonts that cause blank responses
        style: {
            transform: 'scale(1)',
            transformOrigin: 'top left'
        }
    });

    // Restore original container styles
    element.style.height = originalHeight;
    element.style.overflow = originalOverflow;
    element.style.maxHeight = originalMaxHeight;
    
    // Restore buttons
    buttonsToHide.forEach((btn, index) => {
        btn.style.display = originalDisplays[index];
    });
    
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    
    // Dimensions
    const margin = 10;
    const imgWidth = pageWidth - 2 * margin;
    const imgProps = pdf.getImageProperties(imgData);
    const imgHeight = (imgProps.height * imgWidth) / imgProps.width;
    
    let position = margin + 20; // Start below the header

    // Add Premium Header to First Page
    const addHeader = (isFirstPage: boolean) => {
        pdf.setFillColor(255, 90, 95); // #FF5A5F
        pdf.rect(0, 0, pageWidth, 20, 'F');
        pdf.setTextColor(255, 255, 255);
        pdf.setFontSize(16);
        pdf.setFont('helvetica', 'bold');
        pdf.text('YĀTRĀ — AI TRAVEL PLANNER', margin, 14);
        
        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'normal');
        pdf.text(title, pageWidth - margin, 14, { align: 'right' });
    };

    addHeader(true);
    
    // Draw the image
    pdf.addImage(imgData, 'PNG', margin, position, imgWidth, imgHeight);
    
    let heightLeft = imgHeight - (pageHeight - position);

    while (heightLeft > 0) {
        position -= pageHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', margin, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
    }

    // Add Footer across all pages
    const pageCount = pdf.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
        pdf.setPage(i);
        pdf.setFontSize(8);
        pdf.setTextColor(150, 150, 150);
        pdf.text('Generated by YatraMatrix', margin, pageHeight - 5);
        pdf.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 5, { align: 'right' });
    }

    pdf.save(fileName);
  } catch (err) {
    console.error('Error generating PDF:', err);
    throw err;
  }
};
